/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import business.Car;

import javax.swing.*;

/**
 *
 * @author wangcong
 */
public class DetailMngFrame extends javax.swing.JFrame {

    private final Car car;

    /**
     * Creates new form DetailMngFrame
     */
    public DetailMngFrame(Car car) {
        this.car = car;
        initComponents();
        if (car == null) {
            return;
        }
        statusCheckBoxAvailable.setSelected("available".equals(car.getStatus()));
        statusCheckBoxUnavailable.setSelected("unavailable".equals(car.getStatus()));
        txtModelNumber.setText(car.getModelNumber());
        txtSerialNumber.setText(car.getSerialNumber());
        txtBrand.setText(car.getBrand());
        txtManufacturers.setText(car.getManufacturers());
        txtCity.setText(car.getCity());
        txtSeatNum.setText(car.getSeatNumber() + "");
        expiredCheckBox.setSelected("expired".equals(car.getMaintain()));
        unexpiredCheckBox.setSelected("unexpired".equals(car.getMaintain()));
        txtUpdate.setText(car.getUpdateTime());
        txtManufactureYear.setText(car.getManufacturerYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblSeatNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblManufacturers = new javax.swing.JLabel();
        lblWhetherMaintain = new javax.swing.JLabel();
        lblUpdateTime = new javax.swing.JLabel();
        lblmanufactureYear = new javax.swing.JLabel();
        statusCheckBoxAvailable = new javax.swing.JCheckBox();
        statusCheckBoxUnavailable = new javax.swing.JCheckBox();
        txtModelNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtManufacturers = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtSeatNum = new javax.swing.JTextField();
        txtManufactureYear = new javax.swing.JTextField();
        txtUpdate = new javax.swing.JTextField();
        unexpiredCheckBox = new javax.swing.JCheckBox();
        expiredCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Uber Details");

        lblStatus.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStatus.setText("Status:");

        lblSerialNumber.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSerialNumber.setText("Serial Number:");

        lblBrand.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblBrand.setText("Brand:");

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCity.setText("City:");

        lblSeatNumber.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSeatNumber.setText("Seat Number:");

        lblModelNumber.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblModelNumber.setText("Model Number:");

        lblManufacturers.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblManufacturers.setText("Manufacturers:");

        lblWhetherMaintain.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblWhetherMaintain.setText("Whether Maintain:");

        lblUpdateTime.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblUpdateTime.setText("Update time");

        lblmanufactureYear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblmanufactureYear.setText("Manufacture Year:");

        statusCheckBoxAvailable.setText("availbale");

        statusCheckBoxUnavailable.setText("unavailbale");

        unexpiredCheckBox.setText("Unexpired");

        expiredCheckBox.setText("Expired");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStatus)
                    .addComponent(lblSerialNumber)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statusCheckBoxAvailable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusCheckBoxUnavailable))
                    .addComponent(lblManufacturers)
                    .addComponent(txtSerialNumber)
                    .addComponent(txtManufacturers)
                    .addComponent(lblSeatNumber)
                    .addComponent(lblUpdateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeatNum)
                    .addComponent(txtUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblModelNumber)
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBrand)
                        .addComponent(txtModelNumber)
                        .addComponent(txtBrand)
                        .addComponent(txtCity)
                        .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblmanufactureYear)
                        .addComponent(lblWhetherMaintain))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(unexpiredCheckBox)
                        .addGap(35, 35, 35)
                        .addComponent(expiredCheckBox)))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusCheckBoxAvailable)
                            .addComponent(statusCheckBoxUnavailable))
                        .addGap(18, 18, 18)
                        .addComponent(lblSerialNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblModelNumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturers)
                    .addComponent(lblCity))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity)
                    .addComponent(txtManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeatNumber)
                    .addComponent(lblWhetherMaintain))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeatNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unexpiredCheckBox)
                    .addComponent(expiredCheckBox))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanufactureYear)
                    .addComponent(lblUpdateTime))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailMngFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailMngFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailMngFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailMngFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailMngFrame(new Car()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox expiredCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacturers;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSeatNumber;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUpdateTime;
    private javax.swing.JLabel lblWhetherMaintain;
    private javax.swing.JLabel lblmanufactureYear;
    private javax.swing.JCheckBox statusCheckBoxAvailable;
    private javax.swing.JCheckBox statusCheckBoxUnavailable;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtManufacturers;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeatNum;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtUpdate;
    private javax.swing.JCheckBox unexpiredCheckBox;
    // End of variables declaration//GEN-END:variables
}
